#!/usr/bin/env python3
#
# Author: Florent Le Coz <louiz@poezio.eu>
#
# This file is part of Ruĝamia.
#
# Ruĝamia is free software: you can redistribute it and/or modify
# it under the terms of the zlib license. See the COPYING file.

# Edit these
FORGE = "http://redmine.poezio.eu" # preferably no trailing /
PROJECT_NAME = "poezio"
SOCKET_FILENAME = "/tmp/rugamia.socket"
ROOM_NAME = "test@muc.poezio.eu"

import subprocess
import socket
import time
import sys

COMMIT_URL = "%(forge)s/projects/%(name)s/repository/revisions/%%s/diff" % {'forge': FORGE, 'name': PROJECT_NAME}

s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
try:
    socket.connect("%s" % SOCKET_FILENAME)
except Exception:
    print("Error: Can’t send message to the bot using socket %s, make sure it is started." % (SOCKET_FILENAME))
    sys.exit(1)

old, new, branch = sys.stdin.read().split()
proc = subprocess.Popen(["git", "log", "--stat", "--oneline", "-C", "--pretty=format:%h%n%an%n%s", "%s..%s" % (old, new)], stdout=subprocess.PIPE)
revlines = [line.decode().strip() for line in proc.stdout.readlines()]

while revlines:
    h, author, subject = revlines.pop(0), revlines.pop(0), revlines.pop(0)
    url = COMMIT_URL % h
    line = revlines.pop(0)
    while line:
        if revlines:
            line = revlines.pop(0)
        else:
            line = ''
    message = "New revision by %s: %s\n%s" % (author, url, subject)
    socket.send(("%s\n%s" % (ROOM_NAME, message)).encode())

socket.close()
